// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import RoleSelectionController from "./role_selection_controller"
application.register("role-selection", RoleSelectionController)

import ToggleDisplayController from "./toggle_display_controller"
application.register("toggle-display", ToggleDisplayController)
